# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Label and Line EditUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#Below is the line which i added extra
from PyQt5.QtGui import QFont


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(40, 50, 170, 24))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_name = QtWidgets.QLabel(self.splitter)
        self.label_name.setObjectName("label_name")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit.setObjectName("lineEdit")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setGeometry(QtCore.QRect(30, 100, 148, 28))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_result = QtWidgets.QLabel(self.splitter_2)
        self.label_result.setObjectName("label_result")
        #Below is the code i have added for fonts,size and color.
        self.label_result.setFont(QFont("Verdana",6))
        #self.label_result.setStyleSheet('background-color:red')
        self.label_result.setStyleSheet('color:red')
        self.pushButton = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton.setObjectName("pushButton")
        #Below are the lines added here
        self.pushButton.clicked.connect(self.click_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QLabel and QLine Edit"))
        self.label_name.setText(_translate("Form", "Name"))
        self.label_result.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "Clcik Here"))

    #Create a new method
    def click_btn(self):
        name = self.lineEdit.text()
        #print(name)
        self.label_result.setText(name)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
