# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '16.RadioButton&GrpBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#Extra
from PyQt5.QtWidgets import QDialog
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize
#change
#class Ui_Dialog(object):
class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(778, 461)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setObjectName("radioButton_3")
        #Extra 2 lines
        self.radioButton_3.setIcon(QIcon("C:\\Users\\Asus-2020\\PycharmProjects\\PyQt\\Dosai.png"))
        self.radioButton_3.setIconSize(QSize(80, 80))
        self.radioButton_3.toggled.connect(self.radio_selected)
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        # Extra 2 lines
        self.radioButton_2.setIcon(QIcon("C:\\Users\\Asus-2020\\PycharmProjects\\PyQt\\Poori.png"))
        self.radioButton_2.setIconSize(QSize(80, 80))
        self.radioButton_2.toggled.connect(self.radio_selected)
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_1.setObjectName("radioButton_1")
        # Extra 3 lines
        self.radioButton_1.setIcon(QIcon("C:\\Users\\Asus-2020\\PycharmProjects\\PyQt\\Briyani.png"))
        self.radioButton_1.setIconSize(QSize(80, 80))
        self.radioButton_1.toggled.connect(self.radio_selected)
        self.horizontalLayout_2.addWidget(self.radioButton_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "RadioButton & GroupBox"))
        self.groupBox.setTitle(_translate("Dialog", "What is your favourite food?"))
        self.radioButton_3.setText(_translate("Dialog", "Dosai"))
        self.radioButton_2.setText(_translate("Dialog", "Poori"))
        self.radioButton_1.setText(_translate("Dialog", "Egg Briyani"))
        self.label.setText(_translate("Dialog", ""))
    #Extra
    def radio_selected(self):
        radio_button = self.sender()

        if radio_button.isChecked():
            self.label.setText("You have Selected : " + radio_button.text())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
