# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '18.CheckBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(514, 414)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_Pizza = QtWidgets.QCheckBox(Dialog)
        self.checkBox_Pizza.setObjectName("checkBox_Pizza")
        #Extra 1 line
        self.checkBox_Pizza.stateChanged.connect(self.checked_item)
        self.verticalLayout_6.addWidget(self.checkBox_Pizza)
        self.checkBox_Pasta = QtWidgets.QCheckBox(Dialog)
        self.checkBox_Pasta.setObjectName("checkBox_Pasta")
        # Extra 1 line
        self.checkBox_Pasta.stateChanged.connect(self.checked_item)
        self.verticalLayout_6.addWidget(self.checkBox_Pasta)
        self.checkBox_Coke = QtWidgets.QCheckBox(Dialog)
        self.checkBox_Coke.setObjectName("checkBox_Coke")
        # Extra 1 line
        self.checkBox_Coke.stateChanged.connect(self.checked_item)
        self.verticalLayout_6.addWidget(self.checkBox_Coke)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.lbl_result = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_result.setFont(font)
        self.lbl_result.setObjectName("lbl_result")
        self.verticalLayout.addWidget(self.lbl_result)
        self.verticalLayout_7.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Regula Price : 20"))
        self.label_2.setText(_translate("Dialog", "Selcect Extra"))
        self.checkBox_Pizza.setText(_translate("Dialog", "Pizza:3"))
        self.checkBox_Pasta.setText(_translate("Dialog", "Pasta:4"))
        self.checkBox_Coke.setText(_translate("Dialog", "Coke:5"))
        self.lbl_result.setText(_translate("Dialog", ""))

    #Extra
    def checked_item(self):
        price=20

        if self.checkBox_Pizza.isChecked():
            price = price + 3
        if self.checkBox_Pasta.isChecked():
            price = price + 4
        if self.checkBox_Coke.isChecked():
            price = price + 5
        self.lbl_result.setText("Total Price is : {}".format(price))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
